### ISSUE TITLE
AWS scale job does not schedule when workload is toggled off

### ISSUE THREAD

**Issue by afcollins** [cloud-bulldozer/scale-ci-deploy#202]
I disabled the workload node via the toggle openshift_toggle_workload_node, and the scale-openshift pod was left pending.

The reason[1] points to the pod affinity constraints[2].
[1]:  Warning  FailedScheduling  39m                  default-scheduler  0/9 nodes are available: 3 node(s) had untolerated taint {node-role.kubernetes.io/master: }, 9 node(s) didn't match Pod's node affinity/selector. preemption: 0/9 nodes are available: 9 Preemption is not helpful for scheduling.

[2]:
```
spec:                                                                                                
  affinity:                                                                                          
    nodeAffinity:        
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/workload
            operator: In                                                                             
            values:
            - ""
```
